### ISSUE TITLE
toast-notification-count issue

### ISSUE THREAD

**Issue by Mohitur669** [Mohitur669/Realtime-Collaborative-Code-Editor#1]
## Known Bugs
- If a user leaves or enters the room, the toast notification number not showing correctly. <br>
    - Like, if I (user1) create a room and user2 joins the same room, then instead of one toast notification, four toast notifications are shown.
    - Now if the user2 leaves, then two toast notifications are shown instead of one. 

Note: The number of toast notification increases more and more if more users join and leaves the room.

**Note:** If you find any other bugs, please let me know. I will try to fix it as soon as possible :)
In case you want to fix it yourself, feel free to make a pull request.

**Comment by Mohitur669** [comment]
1. To solve the toast notification count remove the React strict app component, just normally pass the <App/> component in the index.js
2. After solving that issue an undefined object is showing up on the connected users' screen if a user leaves. To solve this create a check for undefined users like this,
```
socketRef.current.on(ACTIONS.DISCONNECTED, ({ socketId, username }) => {
    if(username){
        toast.success(`${username} left the room`);
        setClients((prevClients) => {
            return prevClients.filter(client => client.socketId !== socketId);
        });
    }
});
```

**Comment by Mohitur669** [comment]
The issues are fixed after applying above patch.

**Comment by dilpreetkaur03** [comment]
Code is not running? 
Socket connection failed. Try again is there 
what to do

**Comment by Mohitur669** [comment]
> Code is not running? Socket connection failed. Try again is there what to do

This is the latest working code provided on github. You need to follow the steps given in readme.
Don't you forgot to run server and client. P.S: This whole code is tested only locally.

**Comment by labelurtag** [comment]
Socket connection failed. Try again is there
what to do

**Comment by Mohitur669** [comment]
send a meet link and show me whats going on

**Comment by Mohitur669** [comment]
> 
> Socket connection failed. Try again is there
> what to do

You can send a meeting link, I will show you the steps

**Comment by labelurtag** [comment]
https://teams.live.com/l/invite/FEATNw03IH3DNu2jQE

**Comment by labelurtag** [comment]
sir whether  can you join now

**Comment by monishsoorya31** [comment]
After creating and joining the room, sometimes later a popup says "Socket connection failed" and the room closes automatically, how can I resolve the problem?

**Comment by Mohitur669** [comment]
> After creating and joining the room, sometimes later a popup says "Socket connection failed" and the room closes automatically, how can I resolve the problem?

Are you testing this in localhost?

**Comment by monishsoorya31** [comment]
yes I'm testing in local host

**Comment by Mohitur669** [comment]
use npm instead of yarn

**Comment by monishsoorya31** [comment]
thanks I'll try

**Comment by monishsoorya31** [comment]
<img width="1280" alt="Screenshot 2024-03-09 at 5 26 20 PM" src="https://github.com/Mohitur669/Realtime-Collaborative-Code-Editor/assets/88651758/9c91bfc6-217b-4364-bdda-b4deff32367f">

**Comment by monishsoorya31** [comment]
same error occured

**Comment by Mohitur669** [comment]
> same error occured

The problem is occurring because you have to run `node server.js` and `npm start` into different terminals. Both should be running at the same time.

**Comment by Mohitur669** [comment]
sent you a connection req in LinkedIn .. message a google meeting link there

**Comment by rajatsharma979** [comment]
How did you implemented synchronization of code? Did you use OT libraries like ShareDB, OT.js?
